import Head from 'next/head'
import Tabs from "./components/Tabs"
export default function Home() {


  return (
    <>
      <Head>
        <title>Todo List With FocusTimer </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Tabs/>
    </>
  )
}
